name: 'karevo-dashboard'

services:
  backend:
    build: ./backend
    container_name: karevo-dashboard-api
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app        # Mounts the backend directory to /app inside the container
    environment:
      MONGO_URI: mongodb://karevo:raFWD4Jr4ysCMn4oo138@database:27017/karevo-dashboard?authSource=admin
    depends_on:
      - database
    networks:
      - karevo-network

  frontend:
    build: ./frontend
    container_name: karevo-dashboard-web
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src          # Mount only the source files for hot-reloading
      - ./frontend/public:/app/public
    networks:
      - karevo-network

  database:
    image: mongo:6.0
    container_name: karevo-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: karevo
      MONGO_INITDB_ROOT_PASSWORD: raFWD4Jr4ysCMn4oo138
    volumes:
      - mongodb_data:/data/db
    networks:
      - karevo-network

volumes:
  mongodb_data:

networks:
  karevo-network:
