name: Build and Push Docker Images

on:
  workflow_run:
    workflows:
      - Run Tests
    branches: [ main ]
    types:
      - completed  # Docker image should be built after CI jobs are successful.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images using docker-compose
        run: |
          # Install Docker Compose
          sudo apt-get update
          sudo apt-get install -y docker-compose

          # Build and push images
          docker-compose build
          docker-compose push
